# DEFAULT VALUES
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ["None", "X", "Y", "Both"]
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ["None", "Emboss", "Find Edges", "Contour", "Edge Enhance"]
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSACLE_DEFAULT = False
INVERT_DEFAULT = False

# COLORS
BACKGROUND_COLOR = "#242424"
WHITE = "#FFF"
GRAY = "grey"
BLUE = "#1F6AA5"
DARK_GRAY = "#4A4A4A"
CLOSE_RED = "#8A0606"
SLIDER_BG = "#64686B"
DROPDOWN_MAIN_COLOR = "#444"
DROPDOWN_HOVER_COLOR = "#333"
DROPDOWN_MENU_COLOR = "#666"
